name: ROS 2 CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Build
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: offline_trajectory_provider_package
          target-ros2-distro: humble
          vcs-repo-file-url: offline_trajectory_provided.repos
          skip-tests: true # <-- ONLY build!
          colcon-defaults: |
            {
              "build": {
                "symlink-install": true
              }
            }

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: offline_trajectory_provider_package
          target-ros2-distro: humble
          vcs-repo-file-url: offline_trajectory_provided.repos
          skip-build: true # <-- ONLY test!
          colcon-defaults: |
            {
              "test": {
                "parallel-workers": 2
              }
            }
